# Generated by Django 5.2.17 on 2026-10-02 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField()),
                ('counts_json', models.JSONField()),
                ('status', models.CharField(max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.device')),
            ],
        ),
    ]
