# Generated by Django 5.2.17 on 2026-10-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'base_manager_name': 'objects'},
        ),
    ]
